### ISSUE TITLE
Missing Settings.json

### ISSUE THREAD

**Issue by GoldDust69** [Zaphyk/ingame-solver#1]
Hello, I was looking to try this out. Please can you inform me if this still works with the latest update and how do I fix the issue. When running the script I receive the following error, saying that the settings.json is missing, which it is. 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Player\\Desktop\\ingame-solver-master/settings.json'

Thanks in advance.

**Comment by GoldDust69** [comment]
Nevermind, I rewrote it myself for my needs.

**Comment by maxilevi** [comment]
I didn't include it in the repo in order to have a clean git history, its a simple json so you should be able to figure it out by reading the code. Still, I can send you a full example if you need.

**Comment by GoldDust69** [comment]
It's no problem now. I actually rewrote the script to suit my needs but many thanks for the offer, it is much appreciated!

**Comment by maxilevi** [comment]
Great then, let me know if anything else comes up.
